### PR TITLE
Visual Studio 2015 defines snprintf, so don't define in host.h

### PR DESCRIPTION
**Pull request by dstoup**

### CODE REVIEW

**Comment by vedaldi** [comment]
Thanks, brilliant!

**Comment by vedaldi** [comment]
Thanks!

**Comment by dstoup** [comment]
My pleasure .. thank you!

FYI, not sure if you would be interested in a CMake build system for this project, but if you are, I have created one ( for ease of building VLFeat inside my CMake superbuild ). It's pretty simple, and builds on Linux, Mac and VS 2010 and greater. If that's something you're interested in, I can create a pull request.

**Comment by vedaldi** [comment]
Hi David, cmake is definitely something I have been eyeing for a while, but did not try due to the many complications of compiling for MATALB. Was that a problem for you?

**Comment by dstoup** [comment]
Ah, there's the rub. We're not using any MATLAB features, so didn't include those features. I see now that we only did the work for libvl.

I do believe we've done that here before though since we have several MATLAB users in house. I will take a look and see what's around and whether it could be easily incorporated.

**Pull request merged**
